Add share component
Tech4covid19/trackovid19-web pull request #173
Opened 2020-03-22 21:30 UTC by jpppovoa

2020-03-22 22:14 UTC, bmm requested changes

2020-03-22 22:14 UTC, bmm commented on .gitignore
> +Trackovid19-web/src/environments/environment.ts
Retira do ignore pf

2020-03-22 22:24 UTC, bmm approved these changes

2020-03-22 22:26 UTC, jpppovoa commented on .gitignore
> +Trackovid19-web/src/environments/environment.ts
done tks

2020-03-23 05:50 UTC, fabiofcferreira commented
I refactored the desktop view (social share buttons, paddings, units), adapted the modal to mobile screens and fixed a bug with the modal open status.
It's ready to be merged IMHO.

2020-03-23 07:02 UTC, fabiofcferreira commented
Added redirect from change status step 3 to dashboard view with the modal being automatically displayed (using query parameter `share=true`)

2020-03-23 08:47 UTC, merged