Logout
Tech4covid19/trackovid19-web pull request #83
Opened 2020-03-19 22:42 UTC by jpbordalo

Closes #28

2020-03-19 22:45 UTC, bmm approved these changes

2020-03-19 22:48 UTC, hainakus requested changes
window.href nao é usado tens o router para o angular.

2020-03-19 23:43 UTC, bmm commented on Trackovid19-web/src/app/screens/logout/logout.component.ts
> +    this.usersService.login();
O método devia ser o logout() ?

2020-03-20 00:05 UTC, bmm approved these changes

2020-03-20 00:05 UTC, jpbordalo commented on Trackovid19-web/src/app/screens/logout/logout.component.ts
> +    this.usersService.login();
Right!

2020-03-20 02:21 UTC, merged